### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jlew715/project7#1]
I broke it. :cry: It looks like when I try to submit the form with a blank year, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid blank form inputs being submitted.

Let me know when it's updated and I'll take another look.

**Comment by jlew715** [comment]
should be good to go now

**Comment by chrisvfritz** [comment]
Much better! :+1: It's unbreakable now. :smiley: This doesn't have to be fixed, but since you're diving more deeply into Ruby, I'll focus my feedback there.

Let's take this code here.

``` erb
<%
  holary = Array.new
  holary.clear
  begin
    holidays = HolidApi.get(country: selectedCountry, year: selectedYear, month: selectedMonth)
    for i in 0..holidays.length-1 do
      holary[i] = holidays[i][0]["name"]
    end
  rescue
    holary[0]="ENTER A YEAR PLZ"
  end
%>
<%= holary.join("<br/>")  %>
```

First, I'm going to go through and do a refactor, making it more Ruby-like and fixing some potential issues. Afterwards, I'll go through my changes, explaining each one.

``` erb
<%=
  begin
    holidays = HolidApi.get country: selected_country, year: selected_year, month: selected_month
    holidays.flatten.map { |holiday| holiday['name'] }
  rescue HolidApi::BadRequest
    ['ENTER A YEAR PLZ']
  end.join '<br>'
%>
```

### Array flattening

When we have arrays inside of arrays and we just want the objects at the end, the `.flatten` method is very useful. It can take something like this:

``` ruby
[[1, 2, 3], [4, 5, 6, [7, 8]], 9, 10]
```

And transform it into this:

``` ruby
[[1, 2, 3], [4, 5, 6, [7, 8]], 9, 10].flatten
=> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

### Array transformation

In Ruby, when we want to go through an array and get another array, based on the first array, it's common to chain methods to get the result we want and one of the most commonly used methods for array transformation is `.map`.

It takes one array and spits out another array with a specific transformation on each item.

### Variable naming

The variable naming standard in Ruby is to use underscores to separate words, rather than camelCase.

### The dangers of rescuing from _everything_

When using a general rescue, there's a danger that you could rescue from _too_ much. For example, we probably still want `TypeError` and `UndefinedMethod` exceptions to be thrown. Instead it's better to be as specific as possible, targeting only the exception you're actually trying to catch and handle.

[This discussion](http://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby) goes into more detail on the potential pitfalls and side effects of rescuing from everything.

### Every block returns something

Since every block and every method in Ruby returns something, this allows us to use a more "functional" style of programming (as opposed to an "imperative" style). One common feature of this style is chaining methods together to get what we want (similar to a bunch of pipes in bash).

This can be very useful in generating concise code without a bunch of unnecessary variables. It even allows us to do some things that may look strange in other languages, like calling a method on an `end` in `end.join '<br>'`

### Optional parentheses

In Ruby, parentheses are optional - only necessary sometimes for clarification. It's just like in math, where the order of operations allows us to say `3 - 2 * 6`, without having to specify `3 - (2 * 6)`. It's generally best practice to leave them off unless you really need them.

---

Let me know if you have any questions about any of these! I'm happy to give follow-up feedback.
